BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS Stores (
    store_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    store_code TEXT NOT NULL UNIQUE,
    store_name TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sales_tax NUMERIC(4,2) CHECK(sales_tax >= 0.00 AND sales_tax <= 50.00), --sales tax %
    CONSTRAINT stores_code_not_blank CHECK (btrim(store_code) <> ''),
    CONSTRAINT stores_name_not_blank CHECK (btrim(store_name) <> '')
);

CREATE TABLE IF NOT EXISTS Chocolates (
    chocolate_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_name TEXT UNIQUE NOT NULL, -- e.g. "PB Crml"
    full_name TEXT UNIQUE NOT NULL, -- e.g. "Peanut Butter Caramel"
    chocolate_type TEXT NOT NULL DEFAULT 'basic' CHECK(chocolate_type IN ('basic','seasonal','cocoashot')), --one type per chocolate
    contains TEXT[],
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    chocolate_image TEXT, --optional: image may not exist for inactive/new chocolates
    chocolate_description TEXT,
    extra_charge_cents INTEGER CHECK(extra_charge_cents >= 0)
);


CREATE TABLE IF NOT EXISTS Store_layout (
    store_id UUID NOT NULL REFERENCES Stores(store_id) ON DELETE CASCADE,
    chocolate_id INTEGER NOT NULL REFERENCES chocolates(chocolate_id) ON DELETE RESTRICT,
    display_row SMALLINT NOT NULL CHECK (display_row >= 0),
    display_column SMALLINT NOT NULL CHECK (display_column >= 0),
    is_visible BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (store_id, chocolate_id),
    CONSTRAINT store_chocolate_layout_position_unique UNIQUE (store_id, display_row, display_column)
);


CREATE TABLE IF NOT EXISTS Customers (
    customer_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    phone_number VARCHAR(11) CHECK(phone_number ~ '^[0-9]{11}$'), -- including country code
    rewards_number TEXT, -- can be adjusted based on Cocoa Dolce rewards number format
    customer_email TEXT CHECK(customer_email ~ '^[A-Za-z0-9._%-]+@[A-Za-z0-9.-]+\.[A-Za-z0-9\-]{2,}$')
);

CREATE TABLE IF NOT EXISTS Orders (
    order_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    customer_id UUID REFERENCES Customers(customer_id),
    store_id UUID REFERENCES Stores(store_id)
);


CREATE TABLE IF NOT EXISTS Boxes (
    box_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    box_size INTEGER NOT NULL CHECK(box_size IN (6, 10, 16, 30, 50)),
    box_price_cents INTEGER NOT NULL CHECK(box_price > 0), --cocoashots and other items/deals can change box price
    box_total INTEGER NOT NULL CHECK(box_count > 0 AND box_count <= box_size),
    order_id UUID REFERENCES orders(order_id) ON DELETE SET NULL,
    store_id UUID NOT NULL REFERENCES stores(store_id) ON DELETE RESTRICT,
    capture_seconds NUMERIC(6,2) NOT NULL CHECK(created_seconds > 0),
    image_filename TEXT -- optional in case of image failure
    
);

CREATE TABLE IF NOT EXISTS Box_items (
    box_item_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    box_id UUID NOT NULL REFERENCES Boxes(box_id) ON DELETE CASCADE,
    chocolate_id INTEGER NOT NULL REFERENCES Chocolates(chocolate_id) ON DELETE RESTRICT,
    quantity SMALLINT NOT NULL CHECK (quantity > 0),
    CONSTRAINT box_items_box_chocolate_unique UNIQUE (box_id, chocolate_id)
);


COMMIT;