BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS Stores (
    store_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    store_code TEXT NOT NULL UNIQUE,
    store_name TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sales_tax NUMERIC(4,2) NOT NULL DEFAULT 7.50
        CHECK (sales_tax >= 0.00 AND sales_tax <= 50.00),

    CONSTRAINT stores_code_not_blank CHECK (btrim(store_code) <> ''),
    CONSTRAINT stores_name_not_blank CHECK (btrim(store_name) <> '')
);

CREATE TABLE IF NOT EXISTS Chocolates (
    chocolate_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chocolate_code TEXT NOT NULL UNIQUE,
    short_name TEXT NOT NULL UNIQUE,
    full_name TEXT NOT NULL UNIQUE,
    chocolate_type TEXT NOT NULL DEFAULT 'basic'
        CHECK (chocolate_type IN ('basic', 'seasonal', 'cocoashot')),
    contains TEXT[] NOT NULL DEFAULT '{}',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    chocolate_image TEXT,
    chocolate_description TEXT,
    extra_charge_cents INTEGER NOT NULL DEFAULT 0
        CHECK (extra_charge_cents >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chocolates_code_not_blank CHECK (btrim(chocolate_code) <> ''),
    CONSTRAINT chocolates_short_name_not_blank CHECK (btrim(short_name) <> ''),
    CONSTRAINT chocolates_full_name_not_blank CHECK (btrim(full_name) <> '')
);

CREATE TABLE IF NOT EXISTS Store_layout (
    store_id UUID NOT NULL REFERENCES Stores(store_id) ON DELETE CASCADE,
    chocolate_id INTEGER NOT NULL REFERENCES Chocolates(chocolate_id) ON DELETE RESTRICT,
    display_row SMALLINT NOT NULL CHECK (display_row >= 0),
    display_column SMALLINT NOT NULL CHECK (display_column >= 0),
    is_visible BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (store_id, chocolate_id),
    CONSTRAINT store_chocolate_layout_position_unique
        UNIQUE (store_id, display_row, display_column)
);

CREATE TABLE IF NOT EXISTS Customers (
    customer_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    phone_number VARCHAR(11)
        CHECK (phone_number IS NULL OR phone_number ~ '^[0-9]{11}$'),
    rewards_number TEXT,
    customer_email TEXT
        CHECK (
            customer_email IS NULL
            OR customer_email ~ '^[A-Za-z0-9._%-]+@[A-Za-z0-9.-]+\.[A-Za-z0-9\-]{2,}$'
        )
);

CREATE TABLE IF NOT EXISTS Orders (
    order_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    customer_id UUID REFERENCES Customers(customer_id) ON DELETE SET NULL,
    store_id UUID NOT NULL REFERENCES Stores(store_id) ON DELETE RESTRICT,
    sales_tax NUMERIC(4,2) NOT NULL
        CHECK (sales_tax >= 0.00 AND sales_tax <= 50.00),
    subtotal_cents INTEGER NOT NULL DEFAULT 0 CHECK (subtotal_cents >= 0),
    tax_cents INTEGER NOT NULL DEFAULT 0 CHECK (tax_cents >= 0),
    total_cents INTEGER NOT NULL DEFAULT 0 CHECK (total_cents >= 0)
);

CREATE TABLE IF NOT EXISTS Boxes (
    box_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    box_size INTEGER NOT NULL CHECK (box_size IN (6, 10, 16, 30, 50)),
    box_price_cents INTEGER NOT NULL CHECK (box_price_cents >= 0),
    box_total INTEGER NOT NULL CHECK (box_total > 0 AND box_total <= box_size),
    order_id UUID NOT NULL REFERENCES Orders(order_id) ON DELETE CASCADE,
    store_id UUID NOT NULL REFERENCES Stores(store_id) ON DELETE RESTRICT,
    capture_seconds NUMERIC(8,2)
        CHECK (capture_seconds IS NULL OR capture_seconds >= 0),
    image_filename TEXT,
    completed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Box_items (
    box_item_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    box_id UUID NOT NULL REFERENCES Boxes(box_id) ON DELETE CASCADE,
    chocolate_id INTEGER NOT NULL REFERENCES Chocolates(chocolate_id) ON DELETE RESTRICT,
    quantity SMALLINT NOT NULL CHECK (quantity > 0),
    extra_charge_cents_each INTEGER NOT NULL DEFAULT 0
        CHECK (extra_charge_cents_each >= 0),

    CONSTRAINT box_items_box_chocolate_unique
        UNIQUE (box_id, chocolate_id)
);

CREATE INDEX IF NOT EXISTS idx_orders_store_timestamp
    ON Orders(store_id, order_timestamp DESC);

CREATE INDEX IF NOT EXISTS idx_boxes_order
    ON Boxes(order_id);

CREATE INDEX IF NOT EXISTS idx_boxes_completed
    ON Boxes(completed_at DESC);

CREATE INDEX IF NOT EXISTS idx_box_items_chocolate
    ON Box_items(chocolate_id);

COMMIT;
